### ISSUE TITLE
【通知】请上重修课的同学来此签到

### ISSUE THREAD

**Issue by anheihb03dlj** [anheihb03dlj/learn-python#10]
本周二，2015年4月7日静远楼238第二大节课，部分同学说他们要上重修课，与本课程上课时间有冲突。我无法确认你们所说情况的真实性，因此决定单独开一个帖子，请上重修课的同学来此签到，核实情况后我会酌情考虑。<br>
回帖签到格式要求：
班级   姓名    学号    重修课程名称    重修课上课地点(哪个楼哪个教室)   重修课上课时间(周几第几节课)

如果没有来此签到，我认为该同学以后上课的时候，没有正常理由就不来上课，就视为【**旷课**】处理。

其他看到本帖子的同学帮忙通知一下，thanks~

**Comment by anheihb03dlj** [comment]
本周五2015年4月10日，如果没有同学来此签到，那下次再找借口在我上课的时候说去上重修课，视为旷课处理。
*望同学们洁身自好，撒谎的次数多了，自然就成骗子了~*

**Comment by a133244345** [comment]
14通风一班 路琦 1403050112 军事理论 尔雅204 周四第三节
